vim.lsp.config("lua_ls", {})
vim.lsp.config("gopls", {})
vim.lsp.config("bashls", {})
vim.lsp.config("zls", {})
vim.lsp.config("clangd", {})

vim.lsp.enable("lua_ls")
vim.lsp.enable("gopls")
vim.lsp.enable("bashls")
vim.lsp.enable("zls")
vim.lsp.enable("clangd")
vim.lsp.inlay_hint.enable()

vim.keymap.set("n", "K", vim.lsp.buf.hover, { desc = "Show lsp hover" })
vim.keymap.set("n", "gd", vim.lsp.buf.definition, { desc = "Goto definition" })
vim.keymap.set("n", "<leader>cd", vim.lsp.buf.definition, { desc = "Goto definition" })
vim.keymap.set("n", "<leader>ca", function()
  require("tiny-code-action").code_action()
end, { desc = "Code action" })
vim.keymap.set("n", "<leader>cf", function()
  require("conform").format({ async = true })
end, { desc = "Code format" })
vim.keymap.set("n", "<leader>cr", function()
  vim.lsp.buf.rename()
end, { desc = "Rename" })
